# Generated by Django 5.2.1 on 2025-07-10 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Reading"),
                            ("weekly", "Weekly Reading"),
                            ("monthly", "Monthly Reading"),
                            ("custom", "Custom Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bible_version_id", models.CharField(max_length=50)),
                ("target_chapters_per_day", models.IntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bible_version_id", models.CharField(max_length=50)),
                ("current_book_id", models.CharField(blank=True, max_length=50)),
                ("current_chapter_id", models.CharField(blank=True, max_length=50)),
                ("current_verse_number", models.IntegerField(default=1)),
                ("audio_position", models.FloatField(default=0.0)),
                ("is_audio_mode", models.BooleanField(default=False)),
                ("last_read_date", models.DateField(auto_now=True)),
                ("consecutive_days", models.IntegerField(default=0)),
                ("reading_speed_wpm", models.IntegerField(default=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Progress",
                "verbose_name_plural": "Reading Progress",
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("bible_version_id", models.CharField(max_length=50)),
                ("result_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bible_version_id", models.CharField(max_length=50)),
                ("book_id", models.CharField(blank=True, max_length=50)),
                ("chapter_id", models.CharField(blank=True, max_length=50)),
                ("verse_id", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("reflection", "Reflection"),
                            ("prayer", "Prayer"),
                            ("question", "Question"),
                            ("insight", "Insight"),
                            ("application", "Application"),
                        ],
                        default="reflection",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bible_version_id", models.CharField(max_length=50)),
                ("book_id", models.CharField(max_length=50)),
                ("chapter_id", models.CharField(max_length=50)),
                ("verse_id", models.CharField(max_length=50)),
                ("verse_content", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
                "ordering": ["-created_at"],
                "unique_together": {("user", "verse_id")},
            },
        ),
    ]
