# Generated by Django 5.2.1 on 2025-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_otp_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_auth_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google"),
                    ("apple", "Apple"),
                    ("facebook", "Facebook"),
                    ("github", "GitHub"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("microsoft", "Microsoft"),
                    ("amazon", "Amazon"),
                    ("discord", "Discord"),
                    ("twitch", "Twitch"),
                    ("slack", "Slack"),
                    ("instagram", "Instagram"),
                    ("pinterest", "Pinterest"),
                    ("reddit", "Reddit"),
                    ("snapchat", "Snapchat"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
