# Generated by Django 5.2.1 on 2025-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_social_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("password_setup", "Password Setup"),
                    ("email_change", "Email Change"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
