# Generated by Django 5.2.1 on 2026-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("verse_text", models.TextField()),
                ("verse_reference", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
    ]
