# Generated by Django 5.2.1 on 2025-07-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0002_alter_usergoal_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserGoal",
        ),
    ]
