# Generated by Django 5.2.1 on 2025-07-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biblefamiliarityoption",
            options={"verbose_name_plural": "09. Bible Familiarity Options"},
        ),
        migrations.AlterModelOptions(
            name="denomination",
            options={"verbose_name_plural": "03. Denominations"},
        ),
        migrations.AlterModelOptions(
            name="faithgoal",
            options={"verbose_name_plural": "06. Faith Goals"},
        ),
        migrations.AlterModelOptions(
            name="faithgoaloption",
            options={"verbose_name_plural": "05. Faith Goal Options"},
        ),
        migrations.AlterModelOptions(
            name="faithgoalquestion",
            options={"verbose_name_plural": "04. Faith Goal Questions"},
        ),
        migrations.AlterModelOptions(
            name="journeyreason",
            options={"verbose_name_plural": "02. Journey Reasons"},
        ),
        migrations.AlterModelOptions(
            name="journeyreasonoption",
            options={"verbose_name_plural": "01. Journey Reason Options"},
        ),
        migrations.AlterModelOptions(
            name="tonepreference",
            options={"verbose_name_plural": "08. Tone Preferences"},
        ),
        migrations.AlterModelOptions(
            name="tonepreferenceoption",
            options={"verbose_name_plural": "07. Tone Preference Options"},
        ),
    ]
