# Generated by Django 5.2.1 on 2025-07-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "onboarding",
            "0003_denominationoption_alter_biblefamiliarity_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="biblefamiliarity",
            old_name="bible_familiarity",
            new_name="bible_familiarity_option",
        ),
    ]
