# Generated by Django 5.2.1 on 2025-07-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_rename_bible_version_bibleversion_bible_version_option"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biblefamiliarity",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "11. Bible Familiarity",
            },
        ),
        migrations.AlterModelOptions(
            name="biblefamiliarityoption",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "10. Bible Familiarity Options",
            },
        ),
        migrations.AlterModelOptions(
            name="bibleversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "13. Bible Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="bibleversionoption",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "12. Bible Version Options",
            },
        ),
        migrations.AlterModelOptions(
            name="denomination",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "04. Denominations",
            },
        ),
        migrations.AlterModelOptions(
            name="denominationoption",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "03. Denomination Options",
            },
        ),
        migrations.AlterModelOptions(
            name="faithgoal",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "07. Faith Goals",
            },
        ),
        migrations.AlterModelOptions(
            name="faithgoaloption",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "06. Faith Goal Options",
            },
        ),
        migrations.AlterModelOptions(
            name="faithgoalquestion",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "05. Faith Goal Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="journeyreason",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "02. Journey Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="journeyreasonoption",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "01. Journey Reason Options",
            },
        ),
        migrations.AlterModelOptions(
            name="tonepreference",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "09. Tone Preferences",
            },
        ),
        migrations.AlterModelOptions(
            name="tonepreferenceoption",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "08. Tone Preference Options",
            },
        ),
    ]
