# Generated by Django 5.2.1 on 2025-07-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmtoken",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
