# Generated by Django 5.2.1 on 2025-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0002_alter_chapterread_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("scripture", "Scripture Knowledge"),
                    ("share_faith", "Inspiration Goal"),
                    ("conversation", "Confidence Goal"),
                ],
                max_length=20,
            ),
        ),
    ]
