# Generated by Django 5.2.1 on 2025-08-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0004_usergoal_goal_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergoal",
            name="goal_preference",
        ),
    ]
