# Generated by Django 5.2.1 on 2026-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="apple_product_id",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="revenuecat_entitlement_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="revenuecat_product_id_android",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="revenuecat_product_id_ios",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="active_entitlements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="revenuecat_original_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="revenuecat_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("unpaid", "Unpaid"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("pending", "Pending"),
                    ("free", "Free"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
