# Generated by Django 5.2.1 on 2025-07-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="has_voice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="voice_file",
            field=models.FileField(blank=True, null=True, upload_to="voice_messages/"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="voice_transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
