# Generated by Django 5.2.1 on 2025-07-18 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("onboarding", "0009_rename_option_biblefamiliarityoption_caption_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="bible_familiarity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.biblefamiliarity",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="bible_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.bibleversion",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="denomination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.denomination",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="faith_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.faithgoal",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="journey_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.journeyreason",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tone_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.tonepreference",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
