# Generated by Django 5.2.1 on 2025-07-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatsession_bible_familiarity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
