# Generated by Django 5.2.1 on 2026-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chatmessage_voice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
    ]
