# Generated by Django 5.2.1 on 2025-07-19 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatsession_is_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
